ci: pre: add missing shell property
Fixes the following errors[1]:

    Error: /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml (Line: 6, Col: 7): Required property is missing: shell
    Error: /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml (Line: 6, Col: 7): Required property is missing: shell
    Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml (Line: 6, Col: 7): Required property is missing: shell
       at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
       at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
       at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
    Error: Fail to load /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml

[1] https://github.com/kmk3/dummyrepo/actions/runs/4871811426/jobs/8689227063