Revert "ci: pre: set sh as the default shell"
This reverts commit 2608f64bb86a7c76eb3a9f9c48ff324d7aa4a0bc.

Apparently composite actions do not support this.

From [1]:

    Error: /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml (Line: 10, Col: 7): Required property is missing: shell
    Error: /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml (Line: 15, Col: 7): Required property is missing: shell
    Error: /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml (Line: 10, Col: 7): Required property is missing: shell
    Error: /home/runner/work/dummyrepo/dummyrepo/./.github/actions/pre/action.yml (Line: 15, Col: 7): Required property is missing: shell

[1] https://github.com/kmk3/dummyrepo/actions/runs/4871976935/jobs/8689601609