ci: pre: use sh instead of bash
Duh, this runs in Alpine.

Fixes the following errors[1]:

    Run printf 'Hello from pre\n'
      printf 'Hello from pre\n'
      shell: bash --noprofile --norc -e -o pipefail {0}
      env:
        TERM: dumb
    OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
    Error: Process completed with exit code 126.

[1] https://github.com/kmk3/dummyrepo/actions/runs/4871838189/jobs/8689288808